add scoring mechanisms page
gitcoinco/passport-docs pull request #32
Opened 2023-09-21 14:21 UTC by jmcook1186

Adds page on scoring mechanisms to 'Major Concepts' section

2023-09-22 15:45 UTC, lebraat requested changes
Looks great overall! 

A follow-up task will be to audit a few docs pages for places that we link to 'scorer types' (currently links to Getting access) and relink to this page.

2023-09-22 15:45 UTC, lebraat commented on pages/building-with-passport/major-concepts/scoring-mechanisms.mdx
> +With the Unique Humanity Sorer, the threshold is not applied for you on the server. You receive a numeric value to apply as you see fit.
Scorer is misspelled

2023-09-22 15:45 UTC, lebraat commented on pages/building-with-passport/major-concepts/scoring-mechanisms.mdx
> +## Stamp deduplication
Can we please link to the Stamp deduplication page from this section?

2023-10-03 14:59 UTC, jmcook1186 commented on pages/building-with-passport/major-concepts/scoring-mechanisms.mdx
> +With the Unique Humanity Sorer, the threshold is not applied for you on the server. You receive a numeric value to apply as you see fit.
```suggestion
With the Unique Humanity Scorer, the threshold is not applied for you on the server. You receive a numeric value to apply as you see fit.
```

2023-10-03 15:13 UTC, merged