add info on linea contracts
gitcoinco/passport-docs pull request #56
Opened 2023-11-22 14:20 UTC by jmcook1186

Adds info on Gitcoin contreacts deployed to Linea, plus the Verax schema info

2023-11-30 19:24 UTC, lebraat requested changes

2023-11-30 19:24 UTC, lebraat commented on pages/building-with-passport/major-concepts/onchain-passports.mdx
> +The smart contracts are currently deployed on [OP Mainnet](https://chainlist.org/chain/10) and [Linea](https://chainlist.org/chain/59144) ('live' Ethereum layer 2 networks) and [Base Goerli](https://
If we mention Verax, do you think we should also mention EAS here?

2023-12-01 09:49 UTC, jmcook1186 commented on pages/building-with-passport/tutorials/integrating-onchain-stamp-data.md
> +**Note** You can also check your attestations using the [Ethereum Attestation Service explorer](https://base-goerli.easscan.org). Note that the explorer is deployed on separate subdomains for each ne
The Linea link is to the block explorer for that network (the block explorer homepage). Here you would search for the schema and attestations for your application by their address on that specific network. In the tables, there are direct links to the block explorer search result for each of the relevant assets.

2023-12-01 10:46 UTC, jmcook1186 commented on pages/building-with-passport/major-concepts/onchain-passports.mdx
> +The smart contracts are currently deployed on [OP Mainnet](https://chainlist.org/chain/10) and [Linea](https://chainlist.org/chain/59144) ('live' Ethereum layer 2 networks) and [Base Goerli](https://
Maybe best not to mention Verax here as it could be mistaken for a network equivalent to OP/Goerli.
```suggestion
The smart contracts are currently deployed on [OP Mainnet](https://chainlist.org/chain/10) and [Linea](https://chainlist.org/chain/59144) ('live' Ethereum layer 2 networks) and [Base Goerli](https://chainlist.org/chain/84531) (a test network). Linea users can choose to use EAS or [Verax](https://linea.mirror.xyz/LlLx7IytwRYWQbLlxHr6zoUZjqNQdQ5P95zo3Dcilb0) as its onchain attestation registry, whereas the others use the [Ethereum Attestation Service (EAS)](https://attest.sh) only.
```

2023-12-04 22:39 UTC, lebraat commented on pages/building-with-passport/major-concepts/onchain-passports.mdx
> +The smart contracts are currently deployed on [OP Mainnet](https://chainlist.org/chain/10) and [Linea](https://chainlist.org/chain/59144) ('live' Ethereum layer 2 networks) and [Base Goerli](https://
Minor suggested edit:

```suggestion
The smart contracts are currently deployed on [OP Mainnet](https://chainlist.org/chain/10) and [Linea](https://chainlist.org/chain/59144) ('live' Ethereum layer 2 networks) and [Base Goerli](https://chainlist.org/chain/84531) (a test network). Linea's attestation registry is called [Verax](https://linea.mirror.xyz/LlLx7IytwRYWQbLlxHr6zoUZjqNQdQ5P95zo3Dcilb0), while Optimism is using [Ethereum Attestation Service (EAS)](https://attest.sh)
```

2023-12-04 22:45 UTC, lebraat commented on pages/building-with-passport/tutorials/integrating-onchain-stamp-data.md
> +**Note** You can also check your attestations using the [Ethereum Attestation Service explorer](https://base-goerli.easscan.org). Note that the explorer is deployed on separate subdomains for each ne
Sweet. Thank you for explaining!

2023-12-05 11:07 UTC, jmcook1186 commented on pages/building-with-passport/major-concepts/onchain-passports.mdx
> +The smart contracts are currently deployed on [OP Mainnet](https://chainlist.org/chain/10) and [Linea](https://chainlist.org/chain/59144) ('live' Ethereum layer 2 networks) and [Base Goerli](https://
Is this definitely true? From discord I thought that on Linea a user can choose which registry to use

2023-12-05 16:33 UTC, lebraat commented on pages/building-with-passport/major-concepts/onchain-passports.mdx
> +The smart contracts are currently deployed on [OP Mainnet](https://chainlist.org/chain/10) and [Linea](https://chainlist.org/chain/59144) ('live' Ethereum layer 2 networks) and [Base Goerli](https://
I was incorrect during our initial conversation. Turns out we push directly to EAS or Verax, but we just push less information to Verax since gas fees are higher. 

I'm still trying to prioritize writing up a doc on all this.

2023-12-05 16:58 UTC, merged