update tutorial to use decoder contract
gitcoinco/passport-docs pull request #62
Opened 2023-12-22 16:14 UTC by jmcook1186

updates onchain stamps tutorial to use decoder contract

2024-01-02 20:07 UTC, lebraat requested changes
Handful of comments! Thanks

2024-01-02 20:07 UTC, lebraat commented on pages/building-with-passport/tutorials/integrating-onchain-stamp-data.md
> +Once the contractinstance exists, you can simply call `getPassport` passing in the user address, which is stored in your app's state. If the function call returns some stamp data, you can set the `ha
space between contract/instance
Capitalize Stamp

2024-01-12 16:29 UTC, jmcook1186 commented on pages/building-with-passport/tutorials/integrating-onchain-stamp-data.md
> +Thankfully, there is now an onchaion shortcut to executing all this logicv. The `decoder` contract exposes an API that allows you to simply pass in an address and retrieve the decoded data, rather th
yes - done

2024-01-12 16:32 UTC, jmcook1186 commented on pages/building-with-passport/tutorials/integrating-onchain-stamp-data.md
> +You will also need to load a file containing the weights for individual Stamps so you can calculate a Passport score.
I'm having issues with the `getScore` endpoint in the contract. While we're waiting for some debugging support from the dev team, the app still calculates the score client side, although the Stamps themselves are retrieved directly from the contract.

2024-01-13 14:06 UTC, jmcook1186 commented on pages/building-with-passport/tutorials/integrating-onchain-stamp-data.md
> +You will also need to load a file containing the weights for individual Stamps so you can calculate a Passport score.
update - fixed the issue with getScore() - now the page is updated accordingly

2024-01-31 03:36 UTC, merged